ParentSquare/faulty

- lib/faulty/storage/fault_tolerant_proxy.rb
- spec/storage/fault_tolerant_proxy_spec.rb
It was creating a status object with the old style instead of using an
options object. Also added some basic specs for Storage::FaultTolerantProxy
> Fix a crash when Storage::FaultTolerantProxy created a status stub

- lib/faulty/storage/fault_tolerant_proxy.rb
- spec/circuit_spec.rb
They were using an old API with different arguments. Additionally,
expand the circuit spec to test FaultTolerantProxy so that API
incompatibilities will be detected.
> Fix Storage::FaultTolerantProxy open and reopen methods

- lib/faulty/events/notifier.rb
- spec/events/notifier_spec.rb
If a listener crashes, we capture and output the error. This ensures
that Faulty can continue to operate even if a listener starts failing.
> Handle crashes for event listeners

- lib/faulty/storage/memory.rb
- spec/storage/memory_spec.rb
Instead of clearing the oldest entries, Faulty::Storage::Memory would
clear the newest entries once it became full. Fix this and add a spec
for it.
> Fix bug where memory storage would delete the newest entries

- .rubocop.yml
- .travis.yml
- Gemfile
- bin/console
- faulty.gemspec
- lib/faulty/storage/redis.rb
- spec/spec_helper.rb
- spec/storage/redis_spec.rb
- spec/support/concurrency.rb
The bug happened when multiple clients opened or closed a circuit
concurrently, exposing a bug with the CAS implementation. Fix this bug,
and also add concurrency tests to expose the issue.
Also add support for jruby and truffleruby. This allows us to test
concurrency with real paralllel threads. To add jruby support to specs,
we need to move non-essential gems to the Gemfile instead of the gemspec since
some aren't compatible with jruby.
> Fix redis bug where concurrent CAS requests could crash

- .rubocop.yml
- lib/faulty/result.rb
- lib/faulty/storage/redis.rb
When using compare_and_set, Redis storage would not set an expiration
for the state key. This means that key could be stored indefinitely.
Fix compare_and_set to always set an expiration.
> Fix redis storage to expire state key when using CAS

- .rubocop.yml
- README.md
- lib/faulty.rb
- lib/faulty/cache.rb
- lib/faulty/cache/auto_wire.rb
- lib/faulty/cache/circuit_proxy.rb
- lib/faulty/cache/default.rb
- lib/faulty/cache/fault_tolerant_proxy.rb
- lib/faulty/cache/rails.rb
- lib/faulty/circuit.rb
- lib/faulty/error.rb
- lib/faulty/storage.rb
- lib/faulty/storage/auto_wire.rb
- lib/faulty/storage/circuit_proxy.rb
- lib/faulty/storage/fallback_chain.rb
- lib/faulty/storage/fault_tolerant_proxy.rb
- lib/faulty/storage/memory.rb
- lib/faulty/storage/redis.rb
- spec/cache/auto_wire_spec.rb
- spec/cache/circuit_proxy_spec.rb
- spec/cache/fault_tolerant_proxy_spec.rb
- spec/faulty_spec.rb
- spec/storage/auto_wire_spec.rb
- spec/storage/circuit_proxy_spec.rb
- spec/storage/fallback_chain_spec.rb
- spec/storage/fault_tolerant_proxy_spec.rb
- spec/storage/redis_spec.rb
Add CircuitProxy for wrapping storage and caches in an internal circuit
----------------------
The purpose of circuits is to create separation from the app and its
dependencies, but we were breaking that by creating a hard link between
Faulty and its storage backends. Add CircuitProxy wrappers for storage
and cache so that they use internal circuits to break this hard
dependency.
We use circuits directly, outside the containing scope so that the internal
circuits have their own independent backend and do not create a loop.
This will simply use the Memory storage, so that we have a reliable
internal implementation that we can fall back on.
Add FallbackChain storage for falling back to stable storage
----------------------
Although in many cases it's not bad to default circuits to closed on …
> Add tools for backend fault-tolerance

- .github/workflows/ci.yml
There is no reason to run it multiple times, and it's slow on some
ruby versions.
> Only run rubocop for Ruby 2.7 in CI

- README.md
- lib/faulty.rb
- spec/faulty_spec.rb
Also, passing cache, storage, or notifier to Faulty#circuit now behaves as
expected and overrides the Faulty instance options.
> Allow setting default circuit options on Faulty instances

- lib/faulty/storage/redis.rb
The Redis storage backend unintentionally depended on the ConnectionPool gem for checking configuration.
> Fix Redis storage dependency on ConnectionPool

- lib/faulty.rb
- lib/faulty/cache/auto_wire.rb
- lib/faulty/storage/auto_wire.rb
- spec/cache/auto_wire_spec.rb
- spec/faulty_spec.rb
- spec/spec_helper.rb
- spec/storage/auto_wire_spec.rb
Backwards Compatibility: AutoWire.new has been replaced by AutoWire.wrap
- Switch From AutoWire.new to AutoWire.wrap to remove nesting (it's no
longer a delegate)
- Document AutoWire better
- AutoWire now passes the `circuit` option to CircuitProxy
This allows easier construction of backends with custom CircuitProxy circuits:
```ruby
Faulty.init do |config|
config.notifier = Faulty::Events::Notifier.new(config.listeners || [])
config.storage = Faulty::Storage::AutoWire.wrap(
Faulty::Storage::Redis.new,
circuit: Faulty::Circuit.new('my_storage_circuit', cool_down: 15),
notifier: config.notifier
)
config.cache = Faulty::Cache::AutoWire.wrap(
Faulty::Storage::Redis.new,
circuit: Faulty::Circuit.new('my_cache_circuit', cool_down: 15),
notifier: config.notifier
)
end
```
> Allow passing custom circuit to AutoWire

- .rubocop.yml
- README.md
- lib/faulty.rb
- lib/faulty/circuit.rb
- lib/faulty/error.rb
- lib/faulty/patch.rb
- lib/faulty/patch/base.rb
- lib/faulty/patch/redis.rb
- spec/circuit_spec.rb
- spec/faulty_spec.rb
- spec/patch/base_spec.rb
- spec/patch/redis_spec.rb
- spec/patch_spec.rb
- spec/spec_helper.rb
Potential answer for #13. I'd like to add a few patches for some common dependencies going forward.
One question that still needs to be answered is how will we support various versions of Redis (and other libraries). Will there be official support verified by CI, or is it good enough to test with the latest version? That might be something we need to answer on a case-by-case basis.
> Add support for patches to core dependencies starting with redis

- lib/faulty/circuit.rb
- lib/faulty/storage/interface.rb
- lib/faulty/storage/memory.rb
- lib/faulty/storage/redis.rb
- spec/storage/fallback_chain_spec.rb
It previously required returning a full status object which for Redis required multiple backend calls. Reduce that to just one pipelined call by just returning entries. This also simplifies some race conditions where the status could change out from under a circuit while it is processing a run.
BREAKING CHANGE:
Faulty::Storage::Interface must now return a history array instead of a circuit status object. Custom storage backends must be updated.
> Improve storage #entries performance by returning entries

- lib/faulty/storage/fault_tolerant_proxy.rb
- spec/storage/fault_tolerant_proxy_spec.rb
It was not correctly updated to return empty history on failure, causing
a circuit crash when an error was raised inside the #entries method.
> Fix Storage::FaultTolerantProxy to return empty history on entries fail

- README.md
Going through the events I noticed that it stated "because the circuit is closed" in the case of `circuit_skipped`. I assume this meant to say "because the circuit is open" given that we do not execute it. Quick look at the code would confirm this behavior:
https://github.com/ParentSquare/faulty/blob/2408af2f9f399de79e0f048cd97c793f027cd21f/lib/faulty/circuit.rb#L224
> docs, use correct state in description for skipped event

- .github/workflows/ci.yml
Previously in #15 we added support for Redis 3, but never properly setup CI to run the Redis 3 test. This fixes that oversight.
> Fix CI to set REDIS_VERSION correctly

- lib/faulty/patch/base.rb
The recursion protection in Patch::Base set a fiber-local variable.
However when it was done it never unset the variable, instead it set it
to false. This could result in a slow memory leak as new Redis clients
were created.
This fix simply unsets the variable when unused.
> Fix a potential memory leak in patches

- lib/faulty/patch/redis.rb
- spec/patch/redis_spec.rb
The redis main thread can easily be blocked by a stalled Lua script.
When that happens, the Redis client returns a CommandError. This
change modifies that error to its own unique error class. That allows
Faulty to capture it and treat it as a circuit failure.
Fixes #29
> Capture an error for BUSY redis backend when patched

- bin/benchmark
- lib/faulty/circuit.rb
- lib/faulty/events.rb
- lib/faulty/events/callback_listener.rb
- lib/faulty/events/honeybadger_listener.rb
- lib/faulty/events/log_listener.rb
- lib/faulty/status.rb
Adding benchmarks and fixing a few obvious performance problems
```
Starting circuit benchmarks with 100000 iterations each
user     system      total        real
memory storage             19.241159   0.119957  19.361116 ( 19.479319)
memory storage failures    20.985789   0.131852  21.117641 ( 21.250503)
large memory storage      163.561468   1.452444 165.013912 (166.736117)
Starting extra benchmarks with 1000000 iterations each
user     system      total        real
log listener success        2.939421   0.050259   2.989680 (  3.060945)
log listener failure        4.452318   0.050580   4.502898 (  4.568050)
```
```
Starting circuit benchmarks with 100000 iterations each
user     system      total        real
memory storage              2.776031   0.019284   2.795315 (  2.806418)
memory …
```
> Add initial benchmarks and performance improvements

- README.md
- faulty.gemspec
- lib/faulty.rb
- lib/faulty/cache/auto_wire.rb
- lib/faulty/cache/circuit_proxy.rb
- lib/faulty/cache/fault_tolerant_proxy.rb
- lib/faulty/circuit.rb
- lib/faulty/circuit_registry.rb
- lib/faulty/immutable_options.rb
- lib/faulty/status.rb
- lib/faulty/storage/auto_wire.rb
- lib/faulty/storage/circuit_proxy.rb
- lib/faulty/storage/fallback_chain.rb
- lib/faulty/storage/fault_tolerant_proxy.rb
- lib/faulty/storage/interface.rb
- lib/faulty/storage/memory.rb
- lib/faulty/storage/null.rb
- lib/faulty/storage/redis.rb
- spec/circuit_spec.rb
- spec/faulty_spec.rb
- spec/immutable_options_spec.rb
- spec/patch_spec.rb
- spec/spec_helper.rb
- spec/storage/fallback_chain_spec.rb
- spec/storage/fault_tolerant_proxy_spec.rb
This change causes storage backends to store some options that are
required for calculating circuit status. This means that circuit
statuses can be retrieved accurately without having to manually set the
correct options.
TODO
-----------
when that isn't intended.
Fixes #25
BREAKING CHANGES
----------------------
- Added #get_options and #set_options to Faulty::Storage::Interface.
These will need to be added to any custom backends
- Faulty::Storage::Interface#reset now requires removing options in
addition to other stored values
- Circuit options will now be supplemented by stored options until they
are run. This is technically a breaking change in behavior, although
in most cases this should cause the expected result.
- Circuits are not memoized until they are run. Subsequent calls
to …
> Store circuit options in the backend when run

- lib/faulty/circuit.rb
- lib/faulty/error.rb
- spec/circuit_spec.rb
When we rescue an exception during a circuit failure, we can add the failure cause message to the CircuitTrippedError message.
> Add cause message to CircuitTrippedError

- lib/faulty/circuit.rb
- spec/circuit_spec.rb
If the cache was hit, but it is time to refresh, we still run a circuit.
However, if the circuit then fails, it still returns the cached value.
In this scenario, we weren't recording the failure, but instead, simply
returning the cached value without recording success or failure at all.
Fix this so that if the circuit fails, it will always record that
failure even if it returns a cached value.
> Record failures for cache hits

- lib/faulty.rb
Older versions did not support requiring by the name concurrent-ruby.
The correct name to require it is "concurrent".
> Fix crash for older versions of concurrent-ruby

- lib/faulty/storage/redis.rb
- spec/storage/redis_spec.rb
If the circuit opened_at key was cleared or expired then the Redis
storage backend would crash. Fix this by setting the opened_at time to
its earliest-possible value.
Also change Redis backend to include opened_at in the transaction for
opening and closing circuits. This should reduce the chance that status
and opened_at get out of sync.
> Fix crash in Redis storage backend if opened_at was missing

- lib/faulty.rb
- lib/faulty/circuit.rb
- lib/faulty/deprecation.rb
- lib/faulty/error.rb
- lib/faulty/patch.rb
- lib/faulty/patch/elasticsearch.rb
- lib/faulty/patch/mysql2.rb
- lib/faulty/patch/redis.rb
- spec/circuit_spec.rb
- spec/deprecation_spec.rb
- spec/patch/elasticsearch_spec.rb
- spec/patch_spec.rb
With this change, the granular errors normally raised by Elasticsearch
will be preserved. Previously we were discarding the granular error
information raised by the Elasticsearch client and simply raising
an "Error" subclass. Now we raise a Faulty error which is always a
subclass of whichever error was raised by Elasticsearch itself.
To do this, we add support for procs in the new error_mapper option for
circuits. This allows us to individually map the errors returned by
Elasticsearch.
Add Faulty::Deprecation for deprecation notification
Deprecations
-----------------
- The error_module option is deprecated. Patches should use the error_module
option instead. The option will be removed in 0.9
> Add granular errors for Elasticsearch patch

- lib/faulty/circuit.rb
- lib/faulty/storage/fallback_chain.rb
- lib/faulty/storage/fault_tolerant_proxy.rb
- lib/faulty/storage/interface.rb
- lib/faulty/storage/memory.rb
- lib/faulty/storage/null.rb
- lib/faulty/storage/redis.rb
- spec/storage/circuit_proxy_spec.rb
- spec/storage/fallback_chain_spec.rb
- spec/storage/fault_tolerant_proxy_spec.rb
- spec/storage/memory_spec.rb
- spec/storage/redis_spec.rb
The #entry method previously required history to be always returned.
This API had two problems:
- It is inefficient for cases when history is not required. There is no
way to skip generating history when it is not needed. It is only
needed when evaluating a failure, and for most (success) cases we can
simply return nil.
- It prevents storage backends from implementing their own history
scheme that does not store history in the standard way. For example,
if we wanted a lossy storage mechanism, that would not be possible due
to the need to return exact history.
Instead, we simply request storage backends to return status when it is
necessary. We do this by passing in the previous status. Storage
backends can then calculate the new status and return it when needed.
Benchmarks …
> Return status conditionally for Storage::Interface#entry

- .github/workflows/ci.yml
Since the CODACY_PROJECT_TOKEN is not set
> Skip codacy coverage report for external contributions

- lib/faulty/circuit.rb
- spec/circuit_spec.rb
When I inspect the `circuit` in a console, it overwhelms the console with all the options (a solid few seconds to print all the things). 
How about we represent `Circuit` with a name, state and some circuit options?
Thanks!
> Define an inspect method that represent circuit

- CHANGELOG.md
- lib/faulty.rb
- lib/faulty/storage/redis.rb
- spec/circuit_spec.rb
- spec/storage/redis_spec.rb
Allows more precision when calculating circuit status if needed.
Benchmarks report no significant change to performance for in-memory or redis storage adapters.
> Change current_time to a float

- lib/faulty/circuit.rb
- spec/circuit_spec.rb
* The 3 argument form of `Storage::Interface#entry` deprecated in 0.8.5 is now
removed.
* The `error_module` circuit option deprecated in 0.8.5 is now removed.
> Remove features deprecated in 0.8.5

- .github/workflows/ci.yml
- README.md
- lib/faulty/circuit.rb
- lib/faulty/patch/redis.rb
- lib/faulty/patch/redis/middleware.rb
- lib/faulty/patch/redis/patch.rb
- spec/patch/redis_spec.rb
Adds support for redis gem version 5 in the redis patch. Using this patch with Redis 5 will require changing how faulty is specified for Redis connections, so this updates the documentation as well to reflect those different configuration mechanisms.
> Add Redis 5 support for patch

- README.md
> Fix event name typo in README

- README.md
This PR aims to adjust the Stoplight info in the `Alternatives` section.
Addresses #75
> docs: Adjust info about Stoplight
